### ISSUE TITLE
Publish Docker image with a customizable RIE endpoint

### ISSUE THREAD

**Issue by Maks3w** [eagletmt/aws-lambda-rie-gateway#1]
Thanks for develop this bridge.

Could you publish this project as a Docker image and allow to customize the RIE endpoint value (Env var or CMD argument)

Thanks again

**Comment by eagletmt** [comment]
Because I personally don't prefer Docker Hub, I've published the Docker image to GitHub.
https://github.com/users/eagletmt/packages/container/package/aws-lambda-rie-gateway
